# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\app\program\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\app\program\cmake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Administrator\Desktop\OrderAnalyse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Administrator\Desktop\OrderAnalyse

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:\app\program\cmake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\app\program\cmake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Administrator\Desktop\OrderAnalyse\CMakeFiles C:\Users\Administrator\Desktop\OrderAnalyse\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Administrator\Desktop\OrderAnalyse\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Counter

# Build rule for target.
Counter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Counter
.PHONY : Counter

# fast build rule for target.
Counter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/build
.PHONY : Counter/fast

Data.obj: Data.cpp.obj
.PHONY : Data.obj

# target to build an object file
Data.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/Data.cpp.obj
.PHONY : Data.cpp.obj

Data.i: Data.cpp.i
.PHONY : Data.i

# target to preprocess a source file
Data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/Data.cpp.i
.PHONY : Data.cpp.i

Data.s: Data.cpp.s
.PHONY : Data.s

# target to generate assembly for a file
Data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/Data.cpp.s
.PHONY : Data.cpp.s

Read.obj: Read.cpp.obj
.PHONY : Read.obj

# target to build an object file
Read.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/Read.cpp.obj
.PHONY : Read.cpp.obj

Read.i: Read.cpp.i
.PHONY : Read.i

# target to preprocess a source file
Read.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/Read.cpp.i
.PHONY : Read.cpp.i

Read.s: Read.cpp.s
.PHONY : Read.s

# target to generate assembly for a file
Read.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/Read.cpp.s
.PHONY : Read.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Counter.dir\build.make CMakeFiles/Counter.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Counter
	@echo ... Data.obj
	@echo ... Data.i
	@echo ... Data.s
	@echo ... Read.obj
	@echo ... Read.i
	@echo ... Read.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

