name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov libgtest-dev

    - name: Build GTest (Ubuntu needs manual build)
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"

    - name: Build project
      run: |
        cmake --build build --config Debug

    - name: Run tests
      working-directory: ./build
      run: |
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        lcov --capture --directory ./build --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file filtered.info
        genhtml filtered.info --output-directory coverage-report
        echo "Coverage report generated at coverage-report/index.html"

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./coverage-report
