name:  CMake Test

on:
  push:
    branches: ["master"]
jobs:
  Windows_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure & Build
      run: |
        cmake -B build -G "MinGW Makefiles" 
        cmake --build build
        
    - name: Run Tests
      run: |
        $output = ./OrderAnalyse.exe "test/test.csv" "Bin_Location(M)" "Order_ID(M)" "Batch_ID(O)" "output.csv"
        Write-Output $output
        if ($output -like "*Bin_Location(M),Order_ID(M),Batch_ID(O)$'\n'1A01-03-01,1,1$'\n'1A02-03-02,1,1$'\n'1A02-03-05,1,2$'\n'1A03-01-01,5,2$'\n'1A02-03-05:1,2*") {
        Write-Output "::set-output name=status::success"
        } else {
        Write-Output "::set-output name=status::failed"
        exit 1
        }
        
    - name: Handle failure
      if: steps.run_analysis.outputs.status == 'failed'
      run: exit 1


        
    - name: Run Tests (out_put_file)
      run: |
        ./build\OrderAnalyse.exe "test\test.csv" "Bin_Location(M)" "Order_ID(M)" "Batch_ID(O)" "output.csv"

    - name: Check if output.csv exists
      id: check_output
      run: |
        if [ -f "output.csv" ]; then
        echo "::set-output name=file_exists::true"
        else
        echo "::set-output name=file_exists::false"
        exit 1
        fi
      
    - name: Fail if no output
      if: steps.check_output.outputs.file_exists == 'false'
      run: |
        exit 1
