name:  CMake Test

on:
  push:
    branches: ["master"]
jobs:
  Windows_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure & Build
      run: |
        cmake -B build -G "MinGW Makefiles" 
        cmake --build build
        
    - name: Run Tests
      run: |
        $output = ./build\OrderAnalyse.exe "test/test.csv" "Bin_Location(M)" "Order_ID(M)" "Batch_ID(O)" 
        Write-Output $output
        if (-not($output -match "Bin_Location\(M\),Order_ID\(M\),Batch_ID\(O\)" -and 
        $output -match "1A01-03-01,1,1" -and 
        $output -match "1A02-03-02,1,1" -and 
        $output -match "1A02-03-05,1,2" -and 
        $output -match "1A03-01-01,5,2" -and 
        $output -match "1A02-03-05:1,2")) {
        exit 1
        }
        
    - name: Run Tests (out_put_file)
      run: |
        ./build\OrderAnalyse.exe "test\test.csv" "Bin_Location(M)" "Order_ID(M)" "Batch_ID(O)" "output.csv"

    - name: Check if output.csv exists
      id: check_output
      run: |
        if [ -f "output.csv" ]; then
        echo "::set-output name=file_exists::true"
        else
        echo "::set-output name=file_exists::false"
        exit 1
        fi
      
    - name: Fail if no output
      if: steps.check_output.outputs.file_exists == 'false'
      run: |
        exit 1
