name: CI Pipeline

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov gcovr libgtest-dev

    - name: Build and Test
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage"
        cmake --build build
        cd build && ctest --output-on-failure

    - name: Generate Coverage
      run: |
        lcov --capture --directory build --output-file coverage.info \
             --ignore-errors mismatch,unused \
             --rc geninfo_unexecuted_blocks=1
        lcov --remove coverage.info \
             '/usr/*' '*/tests/*' '*/gtest/*' '*/include/c++/*' \
             --output-file filtered.info \
             --ignore-errors unused
        genhtml filtered.info --output-directory coverage \
             --ignore-errors unmapped,unused \
             --title "Linux Coverage Report"
        
        # 同时生成 gcovr 报告作为备选
        gcovr --exclude-unreachable-branches --exclude-throw-branches \
              --html-details coverage/gcovr_report.html

    - uses: actions/upload-artifact@v4
      with:
        name: linux-coverage
        path: |
          coverage
          build/CMakeFiles/*.gcov

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: |
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gtest
          mingw-w64-x86_64-python-gcovr

    - name: Build and Test
      shell: msys2 {0}
      run: |
        cmake -B build -G "MinGW Makefiles" \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
        cmake --build build
        cd build && ctest --output-on-failure

    - name: Generate Coverage
      shell: msys2 {0}
      run: |
        lcov --capture --directory build --output-file coverage.info \
             --ignore-errors mismatch,unused
        lcov --remove coverage.info \
             '*/msys64/*' '*/tests/*' '*/gtest/*' \
             --output-file filtered.info \
             --ignore-errors unused
        genhtml filtered.info --output-directory coverage \
             --ignore-errors unmapped,unused \
             --title "Windows Coverage Report"
        
        # 使用 gcovr 作为备选方案
        gcovr --exclude-unreachable-branches --exclude-throw-branches \
              --html-details coverage/gcovr_report.html

    - uses: actions/upload-artifact@v4
      with:
        name: windows-coverage
        path: |
          coverage
          build/CMakeFiles/*.gcov
